apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kubeflow
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/matty1979/ArgoFlow.git
    targetRevision: HEAD
    path: .
    kustomize:
      version: v4.0.5
  destination:
    server: https://argocd.octo-hatteras.com
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
