apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: knative
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/matty1979/ArgoFlow.git
    targetRevision: HEAD
    path: kubeflow/knative
    kustomize:
      version: v4.0.5
  destination:
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
