apiVersion: v1
kind: Secret
metadata:
  name: memberlist
  namespace: metallb-system
stringData:
  secretkey: "ldJTYkkzE9jIlvtZMqmngQP7Wqt95Cyf1XqadLHUsriFOZpgxTpR+NL/EDNCy59O\naKIIoYjx1rmeCHCmsDF23wBF0a73Dz7Zc+8z2Dom7QyEQ0w5e8KZde+fFPcTlGzX\nj8CgKujUkd01uqJ1gWi/fhhR9akI+flA1yLWNE9Evr4="
